int BoxA, BoxB, BoxC, BoxD, BoxE, BoxF, BoxG;
BoxA = 40;
BoxB = 4;
BoxC = BoxA + BoxB;
BoxD = BoxA - BoxB;
BoxE = BoxA * BoxB;
BoxF = BoxA / BoxB;
BoxG = BoxA % BoxB;
Console.WriteLine("BoxC contains: " + BoxC);
Console.WriteLine("BoxD contains: " + BoxD);
Console.WriteLine("BoxE contains: " + BoxE);
Console.WriteLine("BoxF contains: " + BoxF);
Console.WriteLine("BoxF contains: " + BoxG);
